In [18]:
import csv
import pandas as pd
import numpy as np

In [22]:
with open('/home/atharva/jupyter_lab/facial-expression-analysis-v-2/fer2013.csv', 'r') as csvin:
            data = csv.reader(csvin)
            print(next(data))
            # print(next(data))
            for row in data:
                #print(row)
                face = [int(pixel) for pixel in row[1].split()]
                print(len(face))
                face = np.asarray(face).reshape(48, 48)
                print(face)
                break
                

['emotion', 'pixels', 'Usage']
2304
[[ 70  80  82 ...  52  43  41]
 [ 65  61  58 ...  56  52  44]
 [ 50  43  54 ...  49  56  47]
 ...
 [ 91  65  42 ...  72  56  43]
 [ 77  82  79 ... 105  70  46]
 [ 77  72  84 ... 106 109  82]]


In [6]:
df = pd.read_csv('/home/atharva/jupyter_lab/facial-expression-analysis-v-2/fer2013.csv')

In [7]:
df.head()

emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training

In [23]:
# Python Program illustrating
# numpy.reshape() method

import numpy as geek

# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)

# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
	array2)

# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
	array3)

# Constructs 3D array
array4 = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
	array4)


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
